services:
    # 1. THE FASTAPI INFERENCE CORE
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adr_nlp_api_serving
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=eu-north-1
      - ALLOW_MOCK_MODE=false
      # AWS credentials removed - Handled automatically by EC2 IAM Role in production
    volumes:
      - ./data:/app/data
    restart: always
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s # Increased from 15s to 90s to allow for the S3 download and model loading process to complete before health checks begin.

  # 2. THE STREAMLIT USER FRONTEND
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: adr_nlp_frontend_streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy  # Streamlit waits until BioBERT is fully loaded in memory
    restart: always

  # 3. THE TELEMETRY WATCHDOG
  prometheus:
    image: prom/prometheus:latest
    container_name: adr_nlp_telemetry_prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
    restart: always

  # 4. THE VISUAL METRICS DASHBOARD
  grafana:
    image: grafana/grafana:latest
    container_name: adr_nlp_visualization_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

# GLOBAL STORAGE DECLARATIONS (Strictly at the root level, flush left)
volumes:
  grafana_data:
