FROM python:3.10-slim

# ==========================================================
# Runtime configuration
# ==========================================================

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# ==========================================================
# Install frontend dependencies
# ==========================================================

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir \
    streamlit \
    requests

# ==========================================================
# Copy frontend application
# ==========================================================

COPY app.py .

# ==========================================================
# Streamlit
# ==========================================================

EXPOSE 8501

CMD [
    "streamlit",
    "run",
    "app.py",
    "--server.port=8501",
    "--server.address=0.0.0.0"
]
