version: "3.9"

services:

  # ==========================================================
  # FASTAPI MODEL SERVING
  # ==========================================================
  api:

    image: ${ECR_REGISTRY}/adr-nlp-api:latest

    container_name: adr_nlp_api

    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      AWS_DEFAULT_REGION: eu-north-1
      MODEL_S3_BUCKET: adr-nlp-mlops-bucket-ayesha

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s



  # ==========================================================
  # STREAMLIT FRONTEND
  # ==========================================================
  streamlit:

    image: ${ECR_REGISTRY}/adr-nlp-frontend:latest

    container_name: adr_nlp_frontend

    restart: unless-stopped

    depends_on:
      api:
        condition: service_healthy

    environment:
      API_URL: http://api:8000

    ports:
      - "8501:8501"



  # ==========================================================
  # PROMETHEUS
  # ==========================================================
  prometheus:

    image: prom/prometheus:latest

    container_name: adr_nlp_prometheus

    restart: unless-stopped

    depends_on:
      - api

    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

    ports:
      - "9090:9090"



  # ==========================================================
  # GRAFANA
  # ==========================================================
  grafana:

    image: grafana/grafana:latest

    container_name: adr_nlp_grafana

    restart: unless-stopped

    depends_on:
      - prometheus

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana



volumes:

  grafana-storage:
  